networks:
    backend:
        driver: bridge

services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            PGDATA: /data/postgres
        volumes:
            - ./data/postgres:/data/postgres
        networks:
            - backend
    mysql:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: default
            MYSQL_USER: user
            MYSQL_PASSWORD: 1234
        volumes:
            - ./data/mysql:/var/lib/mysql/
        networks:
            - backend
    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - backend
    elastic:
        image: elasticsearch:8.16.0
        restart: always
        volumes:
            - ./data/elastic:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - backend
        environment:
            - cluster.name=docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            # - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mongo:
        image: mongo
        restart: always
        volumes:
            - ./data/mongo:/data/db
        ports:
            - "27017:27017"
        networks:
            - backend
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
    main:
        restart: always
        build:
            context: ./main
        volumes:
            - ./mysql:/var/lib/mysql
            - ./apps:/var/www
        ports:
            - 22
            - "8000:8000"
            - "8080:8080"
            - "5173:5173"
        tty: true
        networks:
            - backend
        extra_hosts:
            - "host.docker.internal:host-gateway"
    

    
